#####################################################################
# Automatically generated by qmake (2.01a) Tue Aug 14 12:32:49 2012
######################################################################

TEMPLATE = subdirs
CONFIG += ordered debug_and_release

# Directories
SUBDIRS += TestLib CDP_Application

